### ISSUE TITLE
snmp v3 - support

### ISSUE THREAD

**Issue by cpmarvin** [netfishers-onl/BLT#10]
As per title , would be great to have support for snmp v3.

**Comment by AlainMoretti** [comment]
Hello cpmarvin, 
SNMP is here to gather persistent data about the nodes (hostname, interface names) and we don't see a real benefit with usage of SNMPv3. 

Other thing is here at Netfishers we don't have much time left to work on this improvement now. 
Issues opened on Github are taken into account in a best effort manner. 

However, feel free to let us know what is your usage of BLT and how we can help by dropping us an email at contact@netsfishers.onl because we also provide consultancy services.
